"""empty message

Revision ID: 413cc2411fe7
Revises: 
Create Date: 2022-02-28 13:47:01.784025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413cc2411fe7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('species', sa.String(length=30), nullable=True),
    sa.Column('breed', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('vaccination', 'treatment', name='procedureenum'), nullable=True),
    sa.Column('drug', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['animal'], ['animal.animal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedure')
    op.drop_table('animal')
    # ### end Alembic commands ###
